### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by aadilayub** [dreamyguy/validate-color#42]
The `validate-color` package seems to be missing a manifest?

```
gnome-shell-pano on  master [!?] via  v20.12.2 took 3s 
❯ yarn install
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0014: │ validate-color@https://gitpkg.now.sh/dreamyguy/validate-color/src/validate-color: Only some patterns can be imported from legacy lockfiles (not "https://gitpkg.now.sh/dreamyguy/validate-color/src/validate-color#9e890cb48fed5e22027a67d98750232c4ce780f6")
➤ YN0001: │ Error: validate-color@https://gitpkg.now.sh/dreamyguy/validate-color/src/validate-color: Manifest not found
    at AE.find (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:140:120021)
    at async /var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:559:12938
    at async Object.xZe (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:140:53847)
    at async G2.resolve (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:559:12899)
    at async Pd.resolve (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:141:1451)
    at async Pd.resolve (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:141:1451)
    at async /var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:210:7249
    at async Ky (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:140:53910)
    at async ne (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:210:7231)
    at async Promise.allSettled (index 55)
➤ YN0000: └ Completed in 0s 576ms
➤ YN0000: · Failed with errors in 0s 602ms
```

**Comment by aadilayub** [comment]
Sorry, wrong repo!
